povils/phpmnd

README.md
Add strlen to examples as `$password` would evaluate to 1 in original example
=> Add strlen to examples

src/Console/Command.php
@povils requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/povils/phpmnd/
=> Scrutinizer Auto-Fixes

composer.json
Inspired by:
https://github.com/thephpleague/skeleton/blob/03e1f7e71c1a7257f462b253d5eb4dbf2c2403d2/composer.json
=> Add PHPCS & related Composer CLI scripts

README.md
Radiate AppVeyor build status via badge.
=> Radiate AppVeyor build status

.gitattributes, CONTRIBUTING.md, README.md
Start of a contribution guide. 
Open for critique and re-wordings. It'a bit bossy toned currently. :no_mouth:
=> Initial contribution guide. Relates to #20.

README.md, src/Console/Command.php, src/Console/Option.php, src/Extension/ArgumentExtension.php, src/Extension/ArrayExtension.php, src/Extension/AssignExtension.php, src/Extension/ConditionExtension.php, src/Extension/Extension.php, src/Extension/OperationExtension.php, src/Extension/PropertyExtension.php, src/Extension/ReturnExtension.php, src/Extension/SwitchCaseExtension.php, src/ExtensionResolver.php, tests/DetectorTest.php, tests/ExtensionResolverTest.php
=> Add more flexibility to extensions. 'all' option and possibility to remove  extension with minus sign

.gitattributes, CHANGELOG.md
Ready to start change logging. :smile:
=> Initial changelog. Relates to #27.

README.md
Hope you don't mind, that I did some copy editing.
Not quite sure how to word:
> The ``--strings`` option will include strings literal search in code analysis.
As the intention isn't 100% clear to me.
=> Copy edit of documentation

.travis.yml, appveyor.yml
=> Expand PHP versions to test against

README.md, src/Console/Command.php, src/Console/Option.php, src/Visitor/DetectorVisitor.php, tests/Console/CommandTest.php, tests/DetectorTest.php, tests/files/test_1.php
String which are simply numbers should be treated as numbers
eg '1234' should be treated like 1234.
other non numeric strings are still treated as they were
=> Check for numeric strings

README.md, src/Console/Command.php, src/Printer/Console.php, src/Printer/Printer.php, src/Printer/Xml.php
Adding a new output (XML) format. (see #31)
Also introduce a small refactoring for future output format
=> Add XML Output + refactoring on output

README.md, src/Console/Command.php
=> Add whitelist option

src/Extension/ArrayExtension.php, tests/DetectorTest.php, tests/files/test_1.php
=> Fix reading from array

src/Visitor/DetectorVisitor.php, tests/DetectorTest.php, tests/files/test_3.php
Example
const something = 2; should be accepted but having a const array should
not
const something = [1,2,3]; should be something like
const number = 2;
const something = [self::number];
=> Check const for arrays

src/Visitor/DetectorVisitor.php, tests/DetectorTest.php, tests/files/test_1.php
eg when whitelisting 0 and 1, -1 is also whitelisted
This will make it so that -1 would also be conisdered magic unless
explicitly whitelisted
=> Negative numbers incorrectly whitelisted

composer.json
updated the console highlighter, ran some basic usage tests and looks good
=> updated console highlighter

composer.json, src/Console/Command.php
=> Support php-timer 4 and 5

.travis.yml, composer.json
Simply accept PHP8 as a supported PHP version
=> accept PHP8

src/Printer/Xml.php, tests/Printer/XmlTest.php
=> remove magic 12, add XmlTest

tests/Printer/XmlTest.php
sorry, my #130 test has not been passed.
=> hotfix XmlTest

.editorconfig, .github/workflows/ci.yaml, .github/workflows/cs.yaml, README.md, tests/Printer/XmlTest.php
=> Refactor GitHub Actions, add Coding Standards to the CI pipeline.

.github/workflows/ci.yaml, composer.json
This PR brings Symfony 6 support
=> Support symfony 6

.github/workflows/ci.yaml
This PR enables flex as part of shivammathur/setup-php
to avoid issue: https://github.com/povils/phpmnd/runs/7217943038?check_suite_focus=true and composer > 2.3
P.S. A bit blocks our release
=> Add symfony/flex to allow-plugins

.github/workflows/ci.yaml
This PR adds test against PHP 8.2 in CI
=> Test against PHP 8.2

src/Printer/Console.php
=> Fix for missing tput binary

.github/workflows/ci.yaml
This PR adds testing against PHP 8.3 in the pipeline
=> Test against PHP 8.3

.github/workflows/ci.yaml, composer.json
This PR adds symfony 7 support
=> Add Symfony 7 support

CHANGELOG.md, src/Console/Application.php
This PR updates:
- Changelog
- Aplication version
=> Update CHANGELOG, increase application version

CHANGELOG.md, src/Console/Application.php
This PR bumps up version to 3.4.1
=> Bump version to 3.4.1

src/Console/Application.php
Bump version to 3.5.0 ready for release
=> Bump version

.github/workflows/ci.yaml
This PR adds testing against PHP 8.4
=> Test against PHP 8.4
