povils/phpmnd

- .gitattributes
We don't need the Travis CI configuration in releases. 
Lean releases rule of thumb:
> When adding new dotfiles or other non-release related files they have to be `export-ignored`.
> Don't export Travis CI configuration

- .travis.yml
Speed up the Travis CI builds. 
When moving in the direction of gathering code coverage e.g. via [Code Climate](https://codeclimate.com/) Xdebug has to be re-enabled.
> Optimise Travis CI configuration

- bin/phpmnd
- composer.json
The CLI binary has been moved to `bin` to achieve [PDS](http://php-pds.com) compliance.
> Enable PDS compliance

- composer.json
- tests/DetectorTest.php
- tests/FileReportTest.php
* This removes the fixed "platform" config in composer which was set to PHP 5.6.0.
* This sets the minimum PHPUnit version to 5.7 (which has forward compatibility).
* Using `--prefer-lowest` flag with Composer may still install the usual PHPUnit-1.0.0-alpha package which may break.
> Add support for PHPUnit 6+.

- composer.json
- src/ExtensionFactory.php
Ran `composer cs-fix` against the current code base. Also modified `composer cs-fix` and `composer cs-check` to exclude `test/files` because it's files beeing cs-fixed  would break the unit tests.
> Fix coding standard violations

- .travis.yml
- CONTRIBUTING.md
- composer.json
This is just a proof of concept for now.
Since there won't be any usage of [xCIs](https://github.com/povils/phpmnd/issues/25) to guard coding standard violations, utilise `composer cs-check` in Travis CI. The `composer cs-check` is only run against a single version i.e. `7.1` to keep the build fast.
If this gets an okay, I'll remove the on purpose added coding standard violation.
> Enable coding standard compliance guard in Travis CI

- bin/phpmnd
See #45 
Note: There's a few spacing fixes included (7 spaces vs 8 expected for tabbing).
> Fix path when installed as composer require - fixes #45

- appveyor.yml
Resolves some occasional failures in installing PHP where choco has a dependency on something from Windows Update being installed. It's disabled by default on Appveyor (presumably they do it manually from time to time, but not good enough for us here).
> Enable Windows Update service for Appveyor builds

- src/Console/Application.php
Code status wasn't returned from `Application::doRun`:
```bash
$ bin/phpmnd --non-zero-exit-on-violation test.php
phpmnd 1.1.0 by Povilas Susinskas
--------------------------------------------------------------------------------
test.php:9. Magic number: 42
> 9|         if ($x > 42) {
--------------------------------------------------------------------------------
Total of Magic Numbers: 1
Time: 57 ms, Memory: 7.50MB
$ echo $?
1
```
> Fixing exit code

- CHANGELOG.md
- README.md
As the title says, the option `--exclude-name` is actually called `--exclude-file`.
> --exclude-name is actually called --exclude-file

- composer.json
Fixes https://github.com/povils/phpmnd/issues/62.
Unit-Testsuite is green. Also tested on some of my own projects.
```
$ ./vendor/bin/phpunit                                                                                                                                     
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.
.......................                                           23 / 23 (100%)
Time: 117 ms, Memory: 10.00MB
OK (23 tests, 31 assertions)
```
> Widen constrainst for symfony 4 compatibility

- composer.json
- src/Console/Command.php
This change allows phpmnd to be installed alongside packages that depends on phpunit/php-timer 2.x (e.g. PHPUnit 7.0).
> Add compatibility with phpunit/php-timer 2.x

- .travis.yml
- appveyor.yml
- bin/phpmnd
- composer.json
- src/Console/Command.php
#64 Updated the version to 2 and updated the usage in the command class. Also added support for phpunit 7.
Let me know if there's a better way to do this as this might require a major release? 
All the tests pass 
```
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.
.......................                                           23 / 23 (100%)
Time: 102 ms, Memory: 8.00MB
OK (23 tests, 31 assertions)
```
Looks like this will drop support for 5.6 and 7.0
> Update the php timer dep to v2 and use new timer class

- README.md
- src/Console/Option.php
- tests/DetectorTest.php
- tests/files/test_1.php
As a default, intval, strval and floatval will class numbers as not
magic.
This is an easy and clean way to ignore functions while keeping
readability and perfomance of code.
Fixes #82
> Add default ignore functions

- src/Console/Command.php
- src/PHPFinder.php
- tests/Console/CommandTest.php
This allows ` ./bin/phpmnd src/Console src/Extension tests` without affecting  the old command ` ./bin/phpmnd src`
My end goal is allowing folders/filenames interchangeably, so that pre-commit hooks can run on changed files only, but I'd like this to be accepted as first step.
> Allow multiple files and/or directories

- src/Visitor/DetectorVisitor.php
> Ignore negative values when the scalar has no value attribute

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- composer.json
- src/Console/Application.php
I'm a great fan of this tool. However, when trying to install alongside other tools such as phpunit version 9, phpmnd cannot be installed because it needs `phpunit/php-timer:2.0`. Phpunit nowadays uses `phpunit/php-timer:3.0`.
I upgraded to php7.3 as well because new version of used tools have this as a requirement (phpunit v9 and php-timer v3 for example).
Since this is a backwards incompatible change, a new major version should be released for this.
Tests and codestyle are still good.
Please provide feedback if I have missed anything or did something wrong. 
I did not see any issues (specifically) for this, so I decided to work on this myself. Please let me know if I overlooked.
> Update to php 7.3 and update dependencies

- src/Printer/Console.php
When double-clicking file:line the trailing dot also gets selected thus the clipboard cannot be used to paste into the command line: `editor file:line.`
> Make file:line selectable

- box.json.dist
Very few changes on `box` compile action.
Removed 4 recommandations as specified by box itself (version 3.13.0@275b091 2021-05-15 19:13:46 UTC)
```
💡  4 recommendations found:
- The "main" setting can be omitted since is set to its default value
- The "stub" setting can be omitted since is set to its default value
- The compactor "Herrera\Box\Compactor\Php" has been deprecated, use "KevinGH\Box\Compactor\Php" instead.
- The "chmod" setting can be omitted since is set to its default value
```
> Phar distribution improvement

- .gitattributes
- .gitignore
sorted Directory first, and alphabetical order.
and,
* remove `LICENSE export-ignore` and `/README.md export-ignore`
* should not be removed under distribution. 
* see https://github.com/povils/phpmnd/pull/138#discussion_r715981652
* Add `/.* export-ignore`
* to ignore `.github` directories & other dot files.  
* Add `/.phpunit.result.cache`
> maintenance .gitignore & .gitattributes

- README.md
- src/Command/RunCommand.php
- tests/Command/RunCommandTest.php
This PR drop support of `--non-zero-exit-on-violation` option.
The argument is: phpmnd is mostly used in CI where it must fail builds in case any violation is detected so it does not make a lot of sense to use in CI and skip violations.
> Remove --non-zero-exit-on-violation option

- .github/workflows/autoreview.yaml
- .github/workflows/ci.yaml
- .github/workflows/cs.yaml
- README.md
- bin/phpmnd
- composer.json
- phpunit.xml.dist
- src/Command/RunCommand.php
- src/Console/Application.php
- src/Console/Option.php
- src/Container.php
- src/DetectionResult.php
- src/Detector.php
- src/Extension/Extension.php
- src/ExtensionResolver.php
- src/FileReportGenerator.php
- src/HintList.php
- src/PhpParser/FileParser.php
- src/PhpParser/Visitor/DetectionVisitor.php
- src/PhpParser/Visitor/HintVisitor.php
- src/PhpParser/Visitor/ParentConnectorVisitor.php
- src/Printer/Console.php
- src/Printer/Xml.php
- tests/Command/RunCommandTest.php
- tests/DetectorTest.php
This PR:
p.s. It's time to move forward
> Drop php <7.4 support, symfony <4.4, add php 8.1 to pipeline

- CHANGELOG.md
- src/Console/Application.php
> Update release number

- CHANGELOG.md
- composer.json
- src/Container.php
- tests/DetectorTest.php
- tests/PhpParser/FileParserTest.php
- tests/PhpParser/Visitor/BaseVisitorTest.php
This PR adds PHP-Parser 5 support
> Add PHP-Parser 5 support

- .github/workflows/ci.yaml
- src/Console/Application.php
- tests/Application/ApplicationTest.php
Hello,
It's almost always the case when we use an hard coded version (with `Application::VERSION`) to forget to bump it before to push a new release !
To avoid in future to avoid such case, I propose this PR that add a TestCase that is run by CI only when you'll push a tag to repository.
When you push code to a branch, PHPUnit will run this command `vendor/bin/phpunit --exclude-group tags`
```
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.14
Configuration: /shared/backups/forks/phpmnd/phpunit.xml.dist
Random Seed:   1704792472
..........................................                        42 / 42 (100%)
Time: 00:00.231, Memory: 18.00 MB
OK (42 tests, 72 assertions)
```
But when you'll push a tag to repo, PHPUnit will run all tests including this new one …
> Add test to verify that `Application::VERSION` match the latest git tag

- CHANGELOG.md
- composer.json
- src/Console/Application.php
- src/Container.php
- src/Printer/Xml.php
- tests/Printer/XmlTest.php
This PR adds `composer-runtime-api` as dependency in order to get installed version automatically.
This will help mainteners to not to forget to update application version before each release.
Alternative solution to https://github.com/povils/phpmnd/pull/175
> Get application version from composer.lock

- composer.json
This PR adds supprot for phpunit/php-timer 8 which was release a day ago.
> Support phpunit/php-timer 8
